/* ───────────────────────────────────────────────────────────
   PURSUIT · Today — detail surfaces
   DossierScreen · DetailScreen · NudgeModal
   ─────────────────────────────────────────────────────────── */

/* ═══ FULL PREP DOSSIER ══════════════════════════════════════ */
function DossierScreen() {
  const D = window.DOSSIER;
  const app = window.getApp(D.appId);
  return (
    <div className="dos">
      <div className="dos-top">
        <span className="ttl">Interview playbook</span>
        <span className="gen"><span className="sp"><Spark s={13} /></span> Generated by Pursuit · {D.generatedAgo}</span>
      </div>

      <div className="dos-grid">
        {/* left rail */}
        <div className="dos-rail">
          <div className="dos-person">
            <span className="iv-av">{D.interviewer.initials}</span>
            <div className="nm">{D.interviewer.name}</div>
            <div className="ro">{D.interviewer.role}</div>
            <div className="prior">
              {D.interviewer.prior.map((p) => <span key={p}>{p}</span>)}
            </div>
            <div className="links">
              {D.interviewer.links.map((l) => <a key={l}>{l}</a>)}
            </div>
          </div>
          <div className="dos-facts">
            <div className="f"><span className="l">Company</span><span className="v">{app.co}</span></div>
            <div className="f"><span className="l">Role</span><span className="v">{app.role}</span></div>
            <div className="f"><span className="l">When</span><span className="v">{D.meeting.when}</span></div>
            <div className="f"><span className="l">Duration</span><span className="v">{D.meeting.duration}</span></div>
            <div className="f"><span className="l">Where</span><span className="v">{D.meeting.medium}</span></div>
            <div className="f"><span className="l">Round</span><span className="v">{D.meeting.panel}</span></div>
          </div>
          <button className="dos-cta">Add to calendar {ICONS.arrow}</button>
        </div>

        {/* main column */}
        <div className="dos-main">
          <h1>Before you meet <b>{D.interviewer.name}.</b></h1>
          <p className="dek">Everything we could find, distilled into what changes how you show up.</p>

          <div className="dos-sec">
            <div className="kick">Snapshot</div>
            <p className="lead">{D.snapshot}</p>
          </div>

          <div className="dos-sec">
            <div className="kick">How he interviews</div>
            <p className="lead">{D.style.lead}</p>
            <div className="dos-tells">
              {D.style.tells.map((t) => (
                <div className="t" key={t.lbl}><div className="l">{t.lbl}</div><div className="v">{t.val}</div></div>
              ))}
            </div>
          </div>

          <div className="dos-sec">
            <div className="kick">Lands &amp; lands flat</div>
            <div className="dos-two">
              <div className="dos-list good">
                <div className="h"><span className="dot"></span>What lands</div>
                <ul>{D.lands.map((l, i) => <li key={i}>{l}</li>)}</ul>
              </div>
              <div className="dos-list bad">
                <div className="h"><span className="dot"></span>What to avoid</div>
                <ul>{D.avoid.map((l, i) => <li key={i}>{l}</li>)}</ul>
              </div>
            </div>
          </div>

          <div className="dos-sec">
            <div className="kick">Recent signals</div>
            <div className="dos-signals">
              {D.signals.map((s, i) => (
                <div className="dos-sig" key={i}>
                  <div className="when">{s.date}<span className="tg">{s.kind}</span></div>
                  <div><div className="body">{s.body}</div><div className="src">{s.src}</div></div>
                </div>
              ))}
            </div>
          </div>

          <div className="dos-sec">
            <div className="kick">Questions worth asking</div>
            {D.questions.map((q, i) => (
              <div className="dos-q" key={i}>
                <div className="q">“{q.q}”</div>
                <div className="why"><span className="sp"><Spark s={13} /></span>{q.why}</div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

/* ═══ APPLICATION DETAIL ═════════════════════════════════════ */
function DetailScreen({ appId, nav, onLog }) {
  const a = window.getApp(appId);
  const tagFor = (t) => (t ? " " + t : "");
  return (
    <div className="det">
      <div className="det-hd">
        <Logo co={a.short} cls={a.cls} size={56} />
        <div className="meta">
          <div className="co">{a.co}</div>
          <div className="role">{a.role}</div>
          <div className="sub">
            <span>Applied <b>{a.applied}</b></span>
            <span>Source <b>{a.source}</b></span>
            <span>CV <b>{a.cv}</b></span>
          </div>
        </div>
        <Pill status={a.status} label={a.outcome || (window.STATUS_LABEL[a.status])} />
      </div>

      <div className="det-grid">
        <div>
          {a.next ? (
            <div className="det-next">
              <div className="k"><span className="d"></span>Next step · {a.next.in}</div>
              <div className="ttl">{a.next.label} · {a.next.when}</div>
              <div className="mt">
                {a.next.who !== "—" && <span><b>{a.next.who}</b></span>}
                {a.next.medium !== "—" && <span>{a.next.medium}</span>}
                {a.next.mins > 0 && <span>{a.next.mins} min</span>}
              </div>
              <div className="row">
                {a.id === "anthropic"
                  ? <button className="cta" onClick={() => nav("dossier", { appId: a.id })}>Open the playbook {ICONS.arrow}</button>
                  : <button className="cta">Add to calendar {ICONS.arrow}</button>}
                <button className="ghost">Reschedule</button>
              </div>
            </div>
          ) : (
            <div className="det-next" style={{ background: "var(--surface-2)", color: "var(--ink)" }}>
              <div className="k" style={{ color: "var(--mute)" }}><span className="d" style={{ background: a.quiet ? "var(--warm)" : "var(--mute-2)" }}></span>{a.quiet ? "Gone quiet" : "Waiting to hear back"}</div>
              <div className="ttl" style={{ color: "var(--ink)" }}>{a.stage}</div>
              <div className="mt" style={{ color: "var(--mute)" }}><span>No reply in <b style={{ color: "var(--warm-text)" }}>{a.days} days</b> — it might be a good time to reach out to them directly.</span></div>
              <div className="row">
                <button className="cta" style={{ background: "var(--ink)", color: "#fff" }} onClick={onLog}>Log a follow-up {ICONS.arrow}</button>
              </div>
            </div>
          )}

          <div className="sec-lbl">Activity</div>
          <div className="tl">
            {a.timeline.map((e, i) => (
              <div className={"tlrow" + tagFor(e.tag)} key={i}>
                <span className="pt"></span>
                <div className="d">{e.d}</div>
                <div className="t">{e.t}</div>
                <div className="n">{e.n}</div>
              </div>
            ))}
          </div>
        </div>

        {/* side */}
        <div>
          <div className="side-card">
            <div className="ttl">Contact</div>
            {a.recruiter.name !== "—" ? (
              <div className="person">
                <span className="iv-av" style={{ background: "var(--accent)" }}>{a.recruiter.name.split(" ").map((w) => w[0]).join("").slice(0, 2)}</span>
                <div><div className="nm">{a.recruiter.name}</div><div className="ro">{a.recruiter.title}</div></div>
              </div>
            ) : (
              <div className="person"><div><div className="nm" style={{ color: "var(--mute)" }}>No contact yet</div><div className="ro">{a.recruiter.title}</div></div></div>
            )}
          </div>

          <div className="side-card">
            <div className="ttl">Details</div>
            <div className="kv"><span className="l">Status</span><span className="v">{a.outcome || window.STATUS_LABEL[a.status]}</span></div>
            <div className="kv"><span className="l">Last activity</span><span className="v">{a.days ? a.days + " days ago" : "Today"}</span></div>
            <div className="kv"><span className="l">Source</span><span className="v">{a.source}</span></div>
            <div className="kv"><span className="l">Résumé</span><span className="v">{a.cv}</span></div>
          </div>

          <div className="side-card">
            <div className="ttl">Actions</div>
            <div className="side-act">
              {(!a.next || a.quiet) && <button onClick={onLog}><span className="ic">{ICONS.note}</span>Log a follow-up</button>}
              <button><span className="ic">{ICONS.note}</span>Add a note</button>
              <button><span className="ic">{ICONS.cal}</span>Log an event</button>
              <button><span className="ic">{ICONS.link}</span>Open job post</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

Object.assign(window, { DossierScreen, DetailScreen });
