<script>
  // Static mockup of per-round interview prep, split into a shared Company brief
  // (first tab, generated once, true for every round) + per-round interviewer
  // briefs. Mirrors the planned web/src/routes/app/[id]/+page.svelte layout.

  const rounds = [
    { id: 100, label: 'in 2 days · Hiring manager', interviewer: 'Oran Levi', hasPrep: true },
    { id: 101, label: 'in 6 days · Team interview', interviewer: 'Dana Cohen', hasPrep: false }
  ];

  // Tabs: 'company' first, then each round. Default opens on the next round.
  let selected = $state(100);

  const selectedRound = $derived(selected === 'company' ? null : rounds.find(r => r.id === selected));
  const onCompany = $derived(selected === 'company');
  const showInterviewer = $derived(selectedRound && selectedRound.hasPrep);

  let interviewerInput = $state('');
  function select(key) {
    selected = key;
    const r = rounds.find(x => x.id === key);
    interviewerInput = (r && !r.hasPrep) ? r.interviewer : '';
  }
</script>

<svelte:head><title>Round prep — Pursuit</title></svelte:head>

<header class="prev-bar">
  <span class="badge">PREVIEW</span>
  <span class="title">Interview prep — Company (shared) + per-round</span>
  <a href="/app">↩ real app</a>
</header>

<div class="stage">
  <div class="sheet">
    <p class="note">
      <strong>Company</strong> is researched once and is true for every round (sits first).
      Each <strong>round</strong> adds prep about that specific interviewer. Round 1 (Oran)
      has prep; Round 2 (Dana) doesn't yet → generate, without touching the others. Click the chips.
    </p>

    <div class="prep-lead">
      <span class="ai-pill"><span class="spark">✦</span> AI</span>
      <h2>Interview prep</h2>
      {#if onCompany || showInterviewer}
        <p class="prep-gen"><span class="sp">✦</span> Generated by Pursuit · 2h ago{onCompany ? ' · shared across all rounds' : ''}</p>
      {/if}
    </div>

    <div class="round-tabs" role="tablist" aria-label="Interview round">
      <button type="button" role="tab" aria-selected={onCompany}
        class="round-tab company" class:active={onCompany} onclick={() => select('company')}>
        <svg width="12" height="12" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5"><rect x="2.5" y="2" width="11" height="12" rx="1"/><path d="M5.5 5h2M5.5 8h2M5.5 11h2M9.5 5h1.5M9.5 8h1.5"/></svg>
        Company
      </button>
      {#each rounds as r}
        <button type="button" role="tab" aria-selected={selected === r.id}
          class="round-tab" class:active={selected === r.id} onclick={() => select(r.id)}>{r.label}</button>
      {/each}
    </div>

    {#if onCompany}
      <!-- ── Company brief (shared) ── -->
      <section class="card brief-1">
        <div class="b1-hd">
          <div class="logo letter">A</div>
          <div class="b1-titles">
            <div class="b1-name-row"><h3>Acme</h3><span class="ai-pill"><span class="spark">✦</span> AI</span></div>
            <div class="b1-headline">Payments infra for marketplaces — the ledger layer under the checkout.</div>
          </div>
        </div>
        <p class="about">Series C, ~600 people, profitable since last year. Recently shipped a real-time payouts product and is pushing into Europe.</p>
        <div class="b1-facts">
          <div class="b1-cell"><div class="f-lbl">HQ</div><div class="f-val">Tel Aviv</div></div>
          <div class="b1-cell"><div class="f-lbl">Headcount</div><div class="f-val">~600</div></div>
          <div class="b1-cell"><div class="f-lbl">Stage</div><div class="f-val">Series C</div></div>
          <div class="b1-cell"><div class="f-lbl">Founded</div><div class="f-val">2018</div></div>
        </div>
        <div class="b1-process">
          <div class="proc-lbl">Interview process</div>
          <div class="proc-chips">
            <span class="chip">Recruiter</span><span class="proc-arrow">→</span>
            <span class="chip">Hiring manager</span><span class="proc-arrow">→</span>
            <span class="chip">Team interview</span><span class="proc-arrow">→</span>
            <span class="chip">Offer</span>
          </div>
        </div>
      </section>
      <section class="card">
        <div class="card-hd"><h3>What this team grades for</h3><span class="ai-tag">AI · web search</span></div>
        <ul class="la-col"><li class="li"><span class="g lands-g">✓</span><span>Production ownership — they probe rollout, alerting, and what broke.</span></li>
          <li class="li"><span class="g lands-g">✓</span><span>Clear reasoning about money-movement edge cases (idempotency, retries).</span></li>
          <li class="li"><span class="g lands-g">✓</span><span>Pragmatism over architecture-astronautics.</span></li></ul>
      </section>
      <div class="prep-disclaimer">
        Shared across every round · refreshed 2h ago
        <button class="prep-refresh" type="button"><svg width="12" height="12" viewBox="0 0 12 12" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M2 6a4 4 0 1 1 1.2 2.8M2 4v2h2"/></svg> Refresh company brief</button>
      </div>

    {:else if showInterviewer}
      <!-- ── Interviewer brief (this round) ── -->
      <section class="tips">
        <div class="tips-hd"><span class="tips-spark">✦</span><h3>Tips for this round</h3><span class="tips-ai">AI</span></div>
        <ul class="tips-list">
          <li><span class="tip-dot"></span><span>{selectedRound.interviewer.split(' ')[0]} leans practical — bring a concrete shipped example.</span></li>
          <li><span class="tip-dot"></span><span>He's written about on-call culture; have an incident story ready.</span></li>
        </ul>
      </section>
      <section class="card">
        <div class="card-hd"><h3>Your interviewer</h3><span class="ai-tag">AI · 2h ago</span></div>
        <div class="person">
          <div class="p-av">{selectedRound.interviewer.split(' ').map(s => s[0]).join('')}</div>
          <div class="p-info">
            <div class="p-name-row"><h4>{selectedRound.interviewer}</h4><span class="role-tag">Hiring manager</span></div>
            <div class="p-role">Eng Manager, Platform · Acme</div>
            <div class="p-prior">ex-Stripe · ex-Datadog</div>
          </div>
        </div>
        <p class="snapshot">A pragmatic operator who interviews for <em>judgment under ambiguity</em> — less trivia, more "walk me through a call you got wrong."</p>
      </section>
      <section class="la-grid">
        <div class="la-col2 lands"><h3><span class="glyph">✓</span> What lands</h3><ul><li><span class="g">✓</span><span>Owning a tradeoff out loud</span></li><li><span class="g">✓</span><span>Naming the metric you moved</span></li></ul></div>
        <div class="la-col2 avoid"><h3><span class="glyph">✕</span> What to avoid</h3><ul><li><span class="g">✕</span><span>Over-polished, rehearsed arcs</span></li><li><span class="g">✕</span><span>Hand-waving the failure</span></li></ul></div>
      </section>
      <div class="prep-disclaimer">
        About {selectedRound.interviewer} · refreshed 2h ago · always verify before you walk in
        <button class="prep-refresh" type="button"><svg width="12" height="12" viewBox="0 0 12 12" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M2 6a4 4 0 1 1 1.2 2.8M2 4v2h2"/></svg> Refresh</button>
      </div>

    {:else}
      <!-- ── Generate state — round with no interviewer prep yet ── -->
      <div class="generate-card">
        <div class="gen-icon"><svg width="28" height="28" viewBox="0 0 24 24" fill="none"><path d="M12 3C12 7.97 8.97 11 4 11C8.97 11 12 14.03 12 19C12 14.03 15.03 11 20 11C15.03 11 12 7.97 12 3Z" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/></svg></div>
        <h3>Prep for {selectedRound?.label}</h3>
        <p class="gen-sub">We'll research the person interviewing you in this round — background, how they tend to interview, what lands, and questions to ask. The company brief above already covers Acme, so this is just about them.</p>
        <div class="gen-row">
          <input class="gen-input" type="text" placeholder="Interviewer name" bind:value={interviewerInput} />
          <button class="btn-generate">Generate prep</button>
        </div>
        <p class="gen-hint">Won't touch the company brief or other rounds.</p>
      </div>
    {/if}
  </div>
</div>

<style>
  :global(html, body) { background: var(--surface); }
  .prev-bar { position: sticky; top: 0; z-index: 50; display: flex; align-items: center; gap: 12px; padding: 10px 16px; background: var(--ink); color: white; font-size: 12px; }
  .prev-bar .badge { font-family: var(--mono); background: rgba(255,255,255,.15); border-radius: 4px; padding: 2px 7px; letter-spacing: .04em; }
  .prev-bar .title { font-weight: 500; }
  .prev-bar a { margin-left: auto; color: rgba(255,255,255,.7); text-decoration: none; }

  .stage { min-height: calc(100vh - 36px); display: grid; place-items: start center; padding: 40px 24px 80px; }
  .sheet { width: 100%; max-width: 640px; display: flex; flex-direction: column; gap: 4px; }
  .note { font-size: 13px; line-height: 1.5; color: var(--ink-2); background: var(--accent-tint); border: 1px solid var(--accent-tint-2); border-radius: 10px; padding: 12px 14px; margin: 0 0 18px; }

  .prep-lead { margin-bottom: 2px; }
  .prep-lead .ai-pill { display: inline-flex; align-items: center; gap: 6px; font-size: 12px; font-weight: 600; color: var(--accent-text); background: var(--accent-tint); border-radius: 999px; padding: 4px 11px; }
  .prep-lead h2 { font-size: 26px; font-weight: 600; letter-spacing: -0.028em; margin: 12px 0 6px; }
  .prep-gen { font-size: 13px; color: var(--mute); display: inline-flex; align-items: center; gap: 7px; margin: 0; }
  .prep-gen .sp { color: var(--accent); }

  .round-tabs { display: flex; flex-wrap: wrap; gap: 8px; margin: 14px 0 18px; }
  .round-tab { display: inline-flex; align-items: center; gap: 6px; font-family: inherit; font-size: 12.5px; font-weight: 500; color: var(--mute); background: var(--card); border: 1px solid var(--rule); border-radius: 999px; padding: 6px 13px; cursor: pointer; white-space: nowrap; transition: background .12s, color .12s, border-color .12s; }
  .round-tab:hover { color: var(--ink); border-color: var(--accent-tint-2); }
  .round-tab.active { color: var(--accent-text); background: var(--accent-tint); border-color: var(--accent-tint-2); font-weight: 600; }
  .round-tab.company { border-style: dashed; }
  .round-tab.company.active { border-style: solid; }

  .card { background: var(--card); border: 1px solid var(--rule); border-radius: 16px; padding: 20px 22px; margin-top: 14px; }
  .card-hd { display: flex; align-items: center; justify-content: space-between; margin-bottom: 14px; }
  .card-hd h3 { font-size: 15px; font-weight: 600; margin: 0; }
  .ai-tag, .tips-ai { font-size: 10.5px; font-weight: 600; color: var(--accent-text); background: var(--accent-tint); border-radius: 5px; padding: 2px 7px; }

  .b1-hd { display: flex; gap: 14px; align-items: flex-start; }
  .logo.letter { width: 44px; height: 44px; border-radius: 10px; background: var(--ink); color: white; display: grid; place-items: center; font-weight: 600; font-size: 18px; flex: none; }
  .b1-name-row { display: flex; align-items: center; gap: 8px; }
  .b1-name-row h3 { margin: 0; font-size: 17px; font-weight: 600; }
  .b1-headline { font-size: 13.5px; color: var(--ink-2); margin-top: 3px; }
  .about { font-size: 14px; line-height: 1.55; color: var(--ink-2); margin: 14px 0 0; }
  .b1-facts { display: grid; grid-template-columns: repeat(4, 1fr); gap: 10px; margin-top: 16px; }
  .b1-cell { background: var(--surface); border: 1px solid var(--rule); border-radius: 10px; padding: 9px 11px; }
  .f-lbl { font-size: 10.5px; text-transform: uppercase; letter-spacing: .04em; color: var(--mute-2); }
  .f-val { font-size: 13.5px; font-weight: 600; color: var(--ink); margin-top: 2px; }
  .b1-process { margin-top: 16px; }
  .proc-lbl { font-size: 11px; text-transform: uppercase; letter-spacing: .04em; color: var(--mute-2); margin-bottom: 8px; }
  .proc-chips { display: flex; flex-wrap: wrap; align-items: center; gap: 6px; }
  .chip { font-size: 12px; background: var(--accent-tint); color: var(--accent-text); border-radius: 999px; padding: 3px 10px; }
  .proc-arrow { color: var(--mute-2); font-size: 12px; }

  .person { display: flex; gap: 14px; align-items: center; }
  .p-av { width: 46px; height: 46px; border-radius: 50%; display: grid; place-items: center; font-weight: 600; color: var(--accent-text); background: var(--accent-tint); font-size: 15px; }
  .p-name-row { display: flex; align-items: center; gap: 8px; }
  .p-name-row h4 { margin: 0; font-size: 15px; font-weight: 600; }
  .role-tag { font-size: 11px; color: var(--mute); border: 1px solid var(--rule); border-radius: 999px; padding: 1px 8px; }
  .p-role { font-size: 13px; color: var(--ink-2); margin-top: 2px; }
  .p-prior { font-size: 12.5px; color: var(--mute); margin-top: 2px; }
  .snapshot { font-size: 14px; line-height: 1.55; color: var(--ink-2); margin: 14px 0 0; }
  .snapshot :global(em) { color: var(--ink); font-style: normal; font-weight: 600; }

  .tips { background: var(--accent-tint); border: 1px solid var(--accent-tint-2); border-radius: 16px; padding: 16px 20px; margin-top: 14px; }
  .tips-hd { display: flex; align-items: center; gap: 8px; margin-bottom: 10px; }
  .tips-hd h3 { font-size: 14px; font-weight: 600; margin: 0; }
  .tips-spark { color: var(--accent); }
  .tips-list { list-style: none; padding: 0; margin: 0; display: flex; flex-direction: column; gap: 8px; }
  .tips-list li { display: flex; gap: 9px; font-size: 13.5px; line-height: 1.5; color: var(--ink-2); }
  .tip-dot { width: 6px; height: 6px; border-radius: 50%; background: var(--accent); margin-top: 7px; flex: none; }

  .la-col { list-style: none; padding: 0; margin: 0; display: flex; flex-direction: column; gap: 8px; }
  .la-col .li { display: flex; gap: 9px; font-size: 13.5px; line-height: 1.5; color: var(--ink-2); }
  .lands-g { color: #16794d; }
  .la-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-top: 14px; }
  .la-col2 { background: var(--card); border: 1px solid var(--rule); border-radius: 16px; padding: 16px 18px; }
  .la-col2 h3 { font-size: 13.5px; font-weight: 600; margin: 0 0 10px; display: flex; align-items: center; gap: 7px; }
  .la-col2 ul { list-style: none; padding: 0; margin: 0; display: flex; flex-direction: column; gap: 7px; }
  .la-col2 li { display: flex; gap: 8px; font-size: 13px; line-height: 1.45; color: var(--ink-2); }
  .lands .glyph, .lands .g { color: #16794d; }
  .avoid .glyph, .avoid .g { color: #b3261e; }

  .prep-disclaimer { display: flex; align-items: center; justify-content: space-between; gap: 12px; flex-wrap: wrap; font-size: 12px; color: var(--mute); margin-top: 18px; }
  .prep-refresh { display: inline-flex; align-items: center; gap: 6px; font: inherit; font-size: 12px; color: var(--accent-text); background: var(--accent-tint); border: 1px solid var(--accent-tint-2); border-radius: 999px; padding: 5px 12px; cursor: pointer; }

  .generate-card { background: var(--card); border: 1px solid var(--rule); border-radius: 18px; padding: 32px 36px; margin-top: 14px; text-align: center; box-shadow: var(--sh-2); }
  .gen-icon { color: var(--accent); display: grid; place-items: center; margin-bottom: 6px; }
  .generate-card h3 { font-size: 20px; font-weight: 500; letter-spacing: -0.02em; margin: 0 0 10px; }
  .gen-sub { font-size: 13.5px; line-height: 1.55; color: var(--ink-2); margin: 0 auto 16px; max-width: 460px; }
  .gen-row { display: flex; gap: 8px; max-width: 440px; margin: 0 auto; }
  .gen-input { flex: 1; font: inherit; font-size: 13.5px; color: var(--ink); background: var(--surface); border: 1px solid var(--rule); border-radius: 8px; padding: 9px 11px; outline: none; }
  .gen-input:focus { border-color: var(--accent); }
  .btn-generate { font: inherit; font-size: 13.5px; font-weight: 600; color: white; background: var(--accent); border: 0; border-radius: 8px; padding: 9px 16px; cursor: pointer; white-space: nowrap; }
  .gen-hint { font-size: 12px; color: var(--mute); margin: 14px 0 0; }
</style>
