<script>
  // Static mockup of the per-round interview prep selector (no backend).
  // Mirrors web/src/routes/app/[id]/+page.svelte's prep section.

  // Two rounds at the same company. Round 1 (Oran) has prep; round 2 (you)
  // does not yet — selecting it lands on "generate for this round", NOT Oran's
  // brief. "General" holds the legacy single-dossier prep after migration.
  const interviews = [
    { id: 100, label: 'in 2 days · Hiring manager', interviewer: 'Oran Levi', hasPrep: true },
    { id: 101, label: 'in 6 days · Team interview', interviewer: 'Dana Cohen', hasPrep: false }
  ];

  let selectedRoundId = $state(100); // defaults to the next upcoming round
  let interviewerInput = $state('');

  const selectedRound = $derived(
    selectedRoundId === null ? null : interviews.find(iv => iv.id === selectedRoundId)
  );
  // Round 1 has prep; General has the legacy brief; round 2 does not.
  const showBrief = $derived(
    selectedRoundId === null || (selectedRound && selectedRound.hasPrep)
  );
  const briefPerson = $derived(selectedRoundId === null ? 'Oran Levi' : (selectedRound?.interviewer || ''));

  function selectRound(id) {
    selectedRoundId = id;
    const iv = interviews.find(x => x.id === id);
    interviewerInput = (iv && !iv.hasPrep) ? iv.interviewer : '';
  }
</script>

<svelte:head><title>Round prep — Pursuit</title></svelte:head>

<header class="prev-bar">
  <span class="badge">PREVIEW</span>
  <span class="title">Per-round interview prep — round selector</span>
  <a href="/app">↩ real app</a>
</header>

<div class="stage">
  <div class="sheet">
    <p class="note">
      Mockup of the new prep section. <strong>Round 1 (Oran)</strong> has a brief;
      <strong>Round 2 (Dana)</strong> doesn't yet — selecting it offers a fresh generate,
      it never shows Oran's brief. <strong>General</strong> = your existing single dossier
      after the migration. Click the chips.
    </p>

    <!-- ── INTERVIEW PREP ── -->
    <div class="prep-lead">
      <span class="ai-pill"><span class="spark">✦</span> AI</span>
      <h2>Interview prep</h2>
      {#if showBrief}
        <p class="prep-gen"><span class="sp">✦</span> Generated by Pursuit · 2h ago</p>
      {/if}
    </div>

    <div class="round-tabs" role="tablist" aria-label="Interview round">
      {#each interviews as iv}
        <button
          type="button" role="tab"
          aria-selected={selectedRoundId === iv.id}
          class="round-tab" class:active={selectedRoundId === iv.id}
          onclick={() => selectRound(iv.id)}
        >{iv.label}</button>
      {/each}
      <button
        type="button" role="tab"
        aria-selected={selectedRoundId === null}
        class="round-tab" class:active={selectedRoundId === null}
        onclick={() => selectRound(null)}
      >General</button>
    </div>

    {#if showBrief}
      <!-- Existing brief (round 1 or General) -->
      <section class="tips">
        <div class="tips-hd"><span class="tips-spark">✦</span><h3>Tips for this one</h3><span class="tips-ai">AI</span></div>
        <ul class="tips-list">
          <li><span class="tip-dot"></span><span>{briefPerson.split(' ')[0]} leans practical — bring a concrete shipped example, not theory.</span></li>
          <li><span class="tip-dot"></span><span>Expect a rollout / failure-modes probe; have an observability story ready.</span></li>
        </ul>
      </section>

      <section class="card">
        <div class="card-hd"><h3>Your interviewer</h3><span class="ai-tag">AI · 2h ago</span></div>
        <div class="person">
          <div class="p-av">{briefPerson.split(' ').map(s => s[0]).join('')}</div>
          <div class="p-info">
            <div class="p-name-row"><h4>{briefPerson}</h4><span class="role-tag">Hiring manager</span></div>
            <div class="p-role">Eng Manager, Platform · Acme</div>
            <div class="p-prior">ex-Stripe · ex-Datadog</div>
          </div>
        </div>
        <p class="snapshot">A pragmatic operator who interviews for <em>judgment under ambiguity</em> — less trivia, more "walk me through a call you got wrong."</p>
      </section>

      <section class="la-grid">
        <div class="la-col lands">
          <h3><span class="glyph">✓</span> What lands</h3>
          <ul><li><span class="g">✓</span><span>Owning a tradeoff out loud</span></li><li><span class="g">✓</span><span>Naming the metric you moved</span></li></ul>
        </div>
        <div class="la-col avoid">
          <h3><span class="glyph">✕</span> What to avoid</h3>
          <ul><li><span class="g">✕</span><span>Over-polished, rehearsed arcs</span></li><li><span class="g">✕</span><span>Hand-waving the failure</span></li></ul>
        </div>
      </section>

      <div class="prep-disclaimer">
        Synthesised from public posts, talks, and papers · refreshed 2h ago · always verify before you walk in
        <button class="prep-refresh" type="button">
          <svg width="12" height="12" viewBox="0 0 12 12" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M2 6a4 4 0 1 1 1.2 2.8M2 4v2h2"/></svg>
          Refresh prep
        </button>
      </div>
    {:else}
      <!-- Generate state — round with no prep yet -->
      <div class="generate-card">
        <div class="gen-icon">
          <svg width="28" height="28" viewBox="0 0 24 24" fill="none"><path d="M12 3C12 7.97 8.97 11 4 11C8.97 11 12 14.03 12 19C12 14.03 15.03 11 20 11C15.03 11 12 7.97 12 3Z" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/></svg>
        </div>
        <h3>Generate interview prep for {selectedRound?.label}</h3>
        <p class="gen-sub">
          We'll build an AI brief on the person interviewing you — their background, how they tend to interview,
          what lands well, and smart questions to ask. Add a name below to make it about a specific interviewer.
        </p>
        <div class="gen-row">
          <input class="gen-input" type="text" placeholder="Interviewer name (optional)" bind:value={interviewerInput} />
          <button class="btn-generate">Generate interview prep</button>
        </div>
        <p class="gen-hint">Round 1's brief on Oran stays put under its own tab — generating here won't touch it.</p>
      </div>
    {/if}
  </div>
</div>

<style>
  :global(html, body) { background: var(--surface); }

  .prev-bar { position: sticky; top: 0; z-index: 50; display: flex; align-items: center; gap: 12px; padding: 10px 16px; background: var(--ink); color: white; font-size: 12px; }
  .prev-bar .badge { font-family: var(--mono); background: rgba(255,255,255,.15); border-radius: 4px; padding: 2px 7px; letter-spacing: .04em; }
  .prev-bar .title { font-weight: 500; }
  .prev-bar a { margin-left: auto; color: rgba(255,255,255,.7); text-decoration: none; }

  .stage { min-height: calc(100vh - 36px); display: grid; place-items: start center; padding: 40px 24px 80px; }
  .sheet { width: 100%; max-width: 640px; display: flex; flex-direction: column; gap: 4px; }
  .note { font-size: 13px; line-height: 1.5; color: var(--ink-2); background: var(--accent-tint); border: 1px solid var(--accent-tint-2); border-radius: 10px; padding: 12px 14px; margin: 0 0 18px; }

  .prep-lead { margin-bottom: 2px; }
  .prep-lead .ai-pill { display: inline-flex; align-items: center; gap: 6px; font-size: 12px; font-weight: 600; color: var(--accent-text); background: var(--accent-tint); border-radius: 999px; padding: 4px 11px; }
  .prep-lead h2 { font-size: 26px; font-weight: 600; letter-spacing: -0.028em; margin: 12px 0 6px; }
  .prep-gen { font-size: 13px; color: var(--mute); display: inline-flex; align-items: center; gap: 7px; margin: 0; }
  .prep-gen .sp { color: var(--accent); }

  .round-tabs { display: flex; flex-wrap: wrap; gap: 8px; margin: 14px 0 18px; }
  .round-tab { font-family: inherit; font-size: 12.5px; font-weight: 500; color: var(--mute); background: var(--card); border: 1px solid var(--rule); border-radius: 999px; padding: 6px 13px; cursor: pointer; white-space: nowrap; transition: background .12s, color .12s, border-color .12s; }
  .round-tab:hover { color: var(--ink); border-color: var(--accent-tint-2); }
  .round-tab.active { color: var(--accent-text); background: var(--accent-tint); border-color: var(--accent-tint-2); font-weight: 600; }

  .card { background: var(--card); border: 1px solid var(--rule); border-radius: 16px; padding: 20px 22px; margin-top: 14px; }
  .card-hd { display: flex; align-items: center; justify-content: space-between; margin-bottom: 14px; }
  .card-hd h3 { font-size: 15px; font-weight: 600; margin: 0; }
  .ai-tag, .tips-ai { font-size: 10.5px; font-weight: 600; color: var(--accent-text); background: var(--accent-tint); border-radius: 5px; padding: 2px 7px; }
  .person { display: flex; gap: 14px; align-items: center; }
  .p-av { width: 46px; height: 46px; border-radius: 50%; display: grid; place-items: center; font-weight: 600; color: var(--accent-text); background: var(--accent-tint); font-size: 15px; }
  .p-name-row { display: flex; align-items: center; gap: 8px; }
  .p-name-row h4 { margin: 0; font-size: 15px; font-weight: 600; }
  .role-tag { font-size: 11px; color: var(--mute); border: 1px solid var(--rule); border-radius: 999px; padding: 1px 8px; }
  .p-role { font-size: 13px; color: var(--ink-2); margin-top: 2px; }
  .p-prior { font-size: 12.5px; color: var(--mute); margin-top: 2px; }
  .snapshot { font-size: 14px; line-height: 1.55; color: var(--ink-2); margin: 14px 0 0; }
  .snapshot :global(em) { color: var(--ink); font-style: normal; font-weight: 600; }

  .tips { background: var(--accent-tint); border: 1px solid var(--accent-tint-2); border-radius: 16px; padding: 16px 20px; margin-top: 14px; }
  .tips-hd { display: flex; align-items: center; gap: 8px; margin-bottom: 10px; }
  .tips-hd h3 { font-size: 14px; font-weight: 600; margin: 0; }
  .tips-spark { color: var(--accent); }
  .tips-list { list-style: none; padding: 0; margin: 0; display: flex; flex-direction: column; gap: 8px; }
  .tips-list li { display: flex; gap: 9px; font-size: 13.5px; line-height: 1.5; color: var(--ink-2); }
  .tip-dot { width: 6px; height: 6px; border-radius: 50%; background: var(--accent); margin-top: 7px; flex: none; }

  .la-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-top: 14px; }
  .la-col { background: var(--card); border: 1px solid var(--rule); border-radius: 16px; padding: 16px 18px; }
  .la-col h3 { font-size: 13.5px; font-weight: 600; margin: 0 0 10px; display: flex; align-items: center; gap: 7px; }
  .la-col ul { list-style: none; padding: 0; margin: 0; display: flex; flex-direction: column; gap: 7px; }
  .la-col li { display: flex; gap: 8px; font-size: 13px; line-height: 1.45; color: var(--ink-2); }
  .lands .glyph, .lands .g { color: #16794d; }
  .avoid .glyph, .avoid .g { color: #b3261e; }

  .prep-disclaimer { display: flex; align-items: center; justify-content: space-between; gap: 12px; flex-wrap: wrap; font-size: 12px; color: var(--mute); margin-top: 18px; }
  .prep-refresh { display: inline-flex; align-items: center; gap: 6px; font: inherit; font-size: 12px; color: var(--accent-text); background: var(--accent-tint); border: 1px solid var(--accent-tint-2); border-radius: 999px; padding: 5px 12px; cursor: pointer; }

  .generate-card { background: var(--card); border: 1px solid var(--rule); border-radius: 18px; padding: 32px 36px; margin-top: 14px; text-align: center; box-shadow: var(--sh-2); }
  .gen-icon { color: var(--accent); display: grid; place-items: center; margin-bottom: 6px; }
  .generate-card h3 { font-size: 20px; font-weight: 500; letter-spacing: -0.02em; margin: 0 0 10px; }
  .gen-sub { font-size: 13.5px; line-height: 1.55; color: var(--ink-2); margin: 0 auto 16px; max-width: 440px; }
  .gen-row { display: flex; gap: 8px; max-width: 440px; margin: 0 auto; }
  .gen-input { flex: 1; font: inherit; font-size: 13.5px; color: var(--ink); background: var(--surface); border: 1px solid var(--rule); border-radius: 8px; padding: 9px 11px; outline: none; }
  .gen-input:focus { border-color: var(--accent); }
  .btn-generate { font: inherit; font-size: 13.5px; font-weight: 600; color: white; background: var(--accent); border: 0; border-radius: 8px; padding: 9px 16px; cursor: pointer; white-space: nowrap; }
  .gen-hint { font-size: 12px; color: var(--mute); margin: 14px 0 0; }
</style>
